# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170717_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active_status',
            new_name='has_verified_mobile',
        ),
    ]
